<?php
    return [
        /* Credentials
         * *************************************************************************************************************
         * The MPESA API Credentials
         */
        'apps' => [
            'c2b' => [
                'consumer_key' => '',
                'consumer_secret' => '',
            ],
            'b2c' => [
                'consumer_key' => '',
                'consumer_secret' => '',
            ],
            'sandbox_default' => [
                'consumer_key' => 'wYJfGq7PlEDkymEVeJr0go9DJVOkANXep5DEzrwE6Mz3jAce',
                'consumer_secret' => 'dE0qi2keFqWNQrbVHVAAYN3Hta7LAhPJzgw7wOaU94HPsbghkqAkHdAh9dC19A7Z',
            ],
            'sandbox_c2b' => [
                'consumer_key' => '',
                'consumer_secret' => '',
            ],
        ],
        /* File Cache Location
         * **************************************************************************************************************
         * Caching location on the local disk
         */
        'cache_location' => 'cache',

        /* Callback Method
         * **************************************************************************************************************
         * Server Request Method to be used on the Callback URL
         */
        'callback_method' => 'POST',

        /* LNM Online Configurations
         * *************************************************************************************************************
         */
        'lnmo' => [
            /*
             * Paybill Number
             * *********************************************************************************************************
             * The Registered Paybill Number that is used as the Merchant ID
             */
            'short_code' => 174379,
            /*
             * STK Push Callback URL
             * *********************************************************************************************************
             * A fully qualified endpoint that will be queried by Safaricom API
             * on completion or failure of a push transaction
             */
            'callback' => 'https://psctraining.co.ke/api/v1/stk/callback.php',
            /*
             * SAG Passkey
             * *********************************************************************************************************
             * The secre SAG Passkey generated by Safaricom on successful
             * registrations of the Merchant's Paybill Number.
             */
            'passkey' => 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919',
            /*
             * Default Transaction Type
             * *********************************************************************************************************
             * This is the Default Transaction Type set on every STK Push request
             */
            'default_transaction_type' => 'CustomerPaybillOnline'
        ],

        /*
         * C2B Configuration
         * *************************************************************************************************************
         * A fully qualified endpoint that will be queried by Safaricom API
         * on completion or failure of the transaction.
         */
        'c2b' => [
            'initiator_name' => 'vincentkioko',
            'security_credential' => 'Scredit@2018',
            'confirmation_url' => 'https://portal.sterlingcredit.co.ke/api/v1/c2b/confirmation_url.php',
            'validation_url' => 'https://portal.sterlingcredit.co.ke/api/v1/c2b/validation_url.php',
            'on_timeout' => 'Completed',
            'short_code' => '597716',
            'test_phone_number' => '254708374149',
            'default_command_id' => 'CustomerPayBillOnline'
        ],

        /*
         * B2C Configuration
         * *************************************************************************************************************
         * A fully qualified endpoint that will be queried by Safaricom API
         * on completion or failure of the transaction.
         */
        'b2c' => [
            'initiator_name' => 'apiop37',
            'security_credential' => 'Safaricom3021#',
            'short_code' => '603021',
            'default_command_id' => 'BusinessPayment',
            'test_phone_number' => '254708374149',
            'result_url' => 'https://domain/api/v1/b2c/result_url.php',
            'timeout_url' => 'https://domain/api/v1/b2c/timeout_url.php'
        ],

        /*
         * B2B Configuration
         * *************************************************************************************************************
         * A fully qualified endpoint that will be queried by Safaricom API
         * on completion or failure of the transaction.
         */
        'b2b' => [
            'initiator_name' => '',
            'security_credential' => '',
            'default_command_id' => 'BusinessPayBill', # possible values are: BusinessPayBill, MerchantToMerchantTransfer, MerchantTransferFromMerchantToWorking, MerchantServicesMMFAccountTransfer, AgencyFloatAdvance
            'result_url' => 'https://domain/api/v1/b2b/result_url.php',
            'timeout_url' => 'https://domain/api/v1/b2b/timeout_url.php'
        ],

        /*
         * Transaction Status B2C
         * *************************************************************************************************************
         */
        'transaction_status_b2c' => [
            'result_url' => 'https://domain/api/v1/b2c/result_transaction_url.php',
            'timeout_url' => 'https://domain/api/v1/b2c/timeout_transaction_url.php'
        ],

        /*
         * Account Balance B2C
         * *************************************************************************************************************
         */
        'account_balance_b2c' => [
            'timeout_url'=> 'https://domain/api/v1/b2c/timeout_balance_url.php',
            'result_url'=> 'https://domain/api/v1/b2c/result_balance_url.php'
        ],

        /*
         * Account Balance C2B
         * *************************************************************************************************************
         */
        'account_balance_c2b' => [
            'timeout_url'=> 'https://domain/api/v1/c2b/timeout_balance_url.php',
            'result_url'=> 'https://domain/api/v1/c2b/result_balance_url.php'
        ]
    ];
